
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Keans Erol Austria
 */
public class Register extends javax.swing.JFrame {

    String imagePath = null;
    
    public Register() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtRetypePassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        radioArtist = new javax.swing.JRadioButton();
        radioUser = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();
        jLabelLoginHere = new javax.swing.JLabel();
        jLabelImage = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        txtFName = new javax.swing.JTextField();
        jLabelLoginHere1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Register to Art Gallery");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 0, 265, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Username");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 130, 290, 17);

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtUsername);
        txtUsername.setBounds(20, 150, 290, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 190, 290, 17);

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtPassword);
        txtPassword.setBounds(20, 210, 290, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Re-Type Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 250, 290, 17);

        txtRetypePassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtRetypePassword);
        txtRetypePassword.setBounds(20, 270, 290, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Account Type");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 70, 100, 17);

        radioArtist.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioArtist);
        radioArtist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioArtist.setText("Artist");
        jPanel1.add(radioArtist);
        radioArtist.setBounds(90, 90, 63, 25);

        radioUser.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioUser);
        radioUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioUser.setText("User");
        jPanel1.add(radioUser);
        radioUser.setBounds(150, 90, 55, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Profile");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(430, 100, 71, 22);

        btnRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister);
        btnRegister.setBounds(210, 440, 201, 33);

        btnUpload.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpload);
        btnUpload.setBounds(430, 380, 81, 33);

        jLabelLoginHere.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabelLoginHere.setForeground(new java.awt.Color(0, 51, 255));
        jLabelLoginHere.setText("Click Here");
        jLabelLoginHere.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLoginHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginHereMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelLoginHere);
        jLabelLoginHere.setBounds(290, 500, 60, 20);

        jLabelImage.setForeground(new java.awt.Color(153, 153, 153));
        jLabelImage.setName(""); // NOI18N
        jPanel1.add(jLabelImage);
        jLabelImage.setBounds(330, 140, 260, 230);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Last Name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 370, 298, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("First Name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 310, 298, 17);

        txtLName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtLName);
        txtLName.setBounds(20, 390, 290, 30);

        txtFName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtFName);
        txtFName.setBounds(20, 330, 290, 30);

        jLabelLoginHere1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabelLoginHere1.setText("Already have an account?");
        jLabelLoginHere1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginHere1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelLoginHere1);
        jLabelLoginHere1.setBounds(250, 480, 140, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1047, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelLoginHereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginHereMouseClicked
       Login newf = new Login();
       newf.setVisible(true);
       newf.pack();
       newf.setLocationRelativeTo(null);
       this.dispose();
       newf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jLabelLoginHereMouseClicked

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        if(verifData()) {
            try {
                String u = txtUsername.getText();
                String p = String.valueOf(txtPassword.getPassword());
                String f = txtFName.getText();
                String l = txtLName.getText();
                String t = getUserType();
                
                Path path = Paths.get(imagePath);
                byte[] img = Files.readAllBytes(path);
                
                Queries q = new Queries();
                q.insertRegister(u, p, f, l, t, img);
                
                loginPage(); 
            } catch (IOException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        uploadFunction uf = new uploadFunction();
        imagePath = uf.browseImage(jLabelImage);
    }//GEN-LAST:event_btnUploadActionPerformed

    private void jLabelLoginHere1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginHere1MouseClicked
        loginPage();
    }//GEN-LAST:event_jLabelLoginHere1MouseClicked

      public boolean verifData() {
        //[Username - Password] are empty KULANG PA SA RADIO USER/ARTIST/PIC
        if(!txtUsername.getText().isEmpty() && !String.valueOf(txtPassword.getPassword()).isEmpty() && 
                buttonGroup1.getSelection() != null && imagePath != null && !txtLName.getText().isEmpty() && 
                !txtLName.getText().isEmpty()) {
            
            //if password are different
            if(!String.valueOf(txtPassword.getPassword()).equals(String.valueOf(txtRetypePassword.getPassword()))) {
                JOptionPane.showMessageDialog(null, "Passwords are not the same");
                return false;
            }
            else
                return true;
        }
        
        else {
            JOptionPane.showMessageDialog(null, "One or more fields are empty");
            return false;
        }
    }
      
      public String getUserType() {
          String v = null;
          if(radioArtist.isSelected())
              v = "artist";
          if(radioUser.isSelected())
              v = "user";
          
          return v;
      }
      
      public void loginPage() {
            Login lf = new Login();
            lf.setVisible(true);
            lf.pack();
            lf.setLocationRelativeTo(null);
            lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
      }
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnUpload;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelLoginHere;
    private javax.swing.JLabel jLabelLoginHere1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioArtist;
    private javax.swing.JRadioButton radioUser;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRetypePassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
